import React from "react";
import ReactMarkdown from "react-markdown";

export default function RecommendationCard({ recommendation }) {
  if (!recommendation) return null;

  return (
    <div className="recommendation-card">
      <div className="recommendation-header">
        <div className="recommendation-icon">
          <svg
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
          >
            <path d="M12 2a8 8 0 0 1 8 8c0 6-8 12-8 12S4 16 4 10a8 8 0 0 1 8-8z" />
            <circle cx="12" cy="10" r="3" />
          </svg>
        </div>

        <div>
          <h3 className="recommendation-title">
            AI Recommendation Report
          </h3>

          <p className="recommendation-subtitle">
            Generated by Procurement AI
          </p>
        </div>
      </div>

      <div
        className="recommendation-content"
        style={{
          marginTop: "20px",
          lineHeight: "1.8",
        }}
      >
        <ReactMarkdown
          components={{
            h1: ({ children }) => (
              <h1 style={{ marginBottom: 20 }}>{children}</h1>
            ),

            h2: ({ children }) => (
              <h2 style={{ marginBottom: 15 }}>{children}</h2>
            ),

            h3: ({ children }) => (
              <h3 style={{ marginBottom: 10 }}>{children}</h3>
            ),

            p: ({ children }) => (
              <p
                style={{
                  marginBottom: 16,
                }}
              >
                {children}
              </p>
            ),

            ul: ({ children }) => (
              <ul
                style={{
                  paddingLeft: 25,
                  marginBottom: 20,
                }}
              >
                {children}
              </ul>
            ),

            ol: ({ children }) => (
              <ol
                style={{
                  paddingLeft: 25,
                  marginBottom: 20,
                }}
              >
                {children}
              </ol>
            ),

            table: ({ children }) => (
              <table
                className="comparison-table"
                style={{
                  marginTop: 20,
                  marginBottom: 20,
                }}
              >
                {children}
              </table>
            ),

            th: ({ children }) => (
              <th>{children}</th>
            ),

            td: ({ children }) => (
              <td>{children}</td>
            ),

            strong: ({ children }) => (
              <strong
                style={{
                  color: "#2563eb",
                }}
              >
                {children}
              </strong>
            ),
          }}
        >
          {recommendation}
        </ReactMarkdown>
      </div>
    </div>
  );
}